name = "dorysapp"
compatibility_date = "2024-01-01"

# Configuraci√≥n para que Pages use un Worker avanzado
pages_build_output_dir = "."
# Esto le dice que el archivo principal es _worker.js
main = "./_worker.js"

[[d1_databases]]
binding = "DB"
database_name = "dorys_db"
database_id = "b8755e8b-7a99-46ce-b82e-71664c1871ce"